# Generated by Django 4.1.7 on 2023-04-06 11:37

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_Video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
