# Generated by Django 4.1.7 on 2023-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(help_text='Your e-mail address', max_length=254),
        ),
    ]
